version: "3"

services:
  comment-service:
    container_name: comment-service-dev
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    networks:
      - ig-clone-dev
    ports:
      - "3002:3000"
    environment:
      MONGO_USER: dev
      MONGO_PASSWORD: dev
      MONGO_HOST: mongo-dev
      MONGO_DB_NAME: comments
      MONGO_PORT: 27017
      GRPC_HOST: 0.0.0.0
      GRPC_PORT: 3000
      CONSUL_HOST: consul-dev
      CONSUL_PORT: 8500
      KAFKA_SERVERS: kafka-dev:9092

  mongodb:
    image: "mongo"
    container_name: mongo-dev
    networks:
      - ig-clone-dev
    environment:
      - MONGO_INITDB_DATABASE=comments
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - comment-data-dev:/data/db
    ports:
      - "27017:27017"

networks:
  ig-clone-dev:
    external:
      name: ig-clone-dev

volumes:
  comment-data-dev:
    external: true
