version: "3"

networks:
  ig-clone-dev:
    external:
      name: ig-clone-dev

volumes:
  zookeeper-data-dev:
    external: true
  kafka-data-dev:
    external: true

services:
  zookeeper:
    image: bitnami/zookeeper:3
    container_name: zookeeper-dev
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data-dev:/bitnami

  kafka:
    image: bitnami/kafka:2
    ports:
      - "9092:9092"
      - "29092:29092"
    container_name: kafka-dev
    volumes:
      - kafka-data-dev:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-dev:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    depends_on:
      - zookeeper
