
## Cluster settings
cluster:
  enabled: true
  slaveCount: 2

## Specifies the Kubernetes Cluster's Domain Name.
##
clusterDomain: cluster.local

## Use password authentication
usePassword: false


##
## Redis Master parameters
##
master:

  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    size: 1Gi # Override from 8Gi

##
## Redis Slave properties
## Note: service.type is a mandatory parameter
## The rest of the parameters are either optional or, if undefined, will inherit those declared in Redis Master
##
slave:
  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    size: 1Gi # Overridden from 8Gi
