apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-service
  labels:
    app: rest-api-service
spec:
  selector:
    matchLabels:
      app: rest-api-service
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rest-api-service
        tier: frontend
    spec:
      containers:
        - name: rest-api
          image: ppeerttu/rest-api:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
          ports:
          - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
          env:
          - name: NODE_ENV
            value: production
          - name: SERVER_PORT
            value: "3000"
          - name: AUTH_SERVICE
            value: auth-service.default.svc.cluster.local:3000
          - name: CONSUL_HOST
            value: hashicorp-consul-server.default.svc.cluster.local
          - name: IMAGE_SERVICE
            value: image-service.default.svc.cluster.local:3000
          - name: COMMENT_SERVICE
            value: comment-service.default.svc.cluster.local:3000
          - name: USER_SERVICE
            value: user-service.default.svc.cluster.local:3000
          - name: USE_STATIC_ENDPOINTS
            value: "true"
